fragment GlobalParts on Global {
  __typename
  name
  logoName
  role
  location
  email
  hero {
    __typename
    titleFirst
    titleSecond
    description
    currentCompany
  }
  about {
    __typename
    title
    description
  }
  experience {
    __typename
    role
    period
    company
    description
  }
  stack {
    __typename
    core
    creative
    infrastructure
  }
  services
  socials {
    __typename
    title
    url
  }
}

fragment ProjectParts on Project {
  __typename
  title
  slug
  displayId
  order
  category
  year
  client
  description
  longDescription
  challenge
  solution
  image
  tech
  body
}
